name: Code Linting

# CINTENT >> MANUAL_TRIGGER
# on:
#   push:
#     branches: [ main, develop ]
#     tags:
#       - '[0-9]+\.[0-9]+\.[0-9]+'
#       - '[0-9]+\.[0-9]+\.[0-9]+-*'
#   pull_request:
#     branches: [ main, develop ]
on: [repository_dispatch, workflow_dispatch]

jobs:
  run_tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          check-latest: true

      # CINTENT >> INSERT_CINTENT
      - uses: JavidDitty/setup-cintent@3e5b2faf83a2ad32c22a1cd0f86f5f20ea53a5ab

      - name: Install cryoDRGN with dev dependencies
        run: |
          python3 -m pip install .[dev]

      # CINTENT >> REMOVE_COMMIT
      # - name: Run pre-commit checks
      #   run: |
      #     pre-commit run --all-files --show-diff-on-failure

      - name: Run Pyright
        run: |
          pyright --version
          #pyright

      # CINTENT >> INSERT_CINTENT
      - name: Upload CIntent Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ env.CINTENT_ARTIFACT_NAME }}
          path: ${{ env.CINTENT_LOGS }}
